#!/usr/bin/env perl
# $Id: txicmdlist,v 1.5 2012-01-20 18:11:41 karl Exp $
# Copyright 2011, 2012 Free Software Foundation, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Original author: Patrice Dumas.
#
# Output Texinfo command names recognized in the implementation.

BEGIN {
  (my $mydir = $0) =~ s,/[^/]+$,,;
  chomp (my $tpdir = `cd $mydir/../tp && pwd`);
  unshift (@INC, $tpdir);
}

use Texinfo::Common;

print map { "\@$_\n" } sort (keys %Texinfo::Common::all_commands);
