#! /bin/sh
# Copyright (C) 2010 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

if [ z"$srcdir" = 'z' ]; then
  srcdir=.
fi

"$srcdir"/parser_tests.sh "$@" \
 formatting encodings \
 htmlxref htmlxref-only_mono htmlxref-only_split
