@node Top
@top GNU Sample

This manual is for GNU Sample

@menu
* First Chapter::    The first chapter is the
                      only chapter in this sample.
* Index::            Complete index.
@end menu


@node First Chapter
@chapter First Chapter

This is the first chapter.

Here is a numbered list.

@node Index
@unnumbered Index


printindex

@bye

