BEGIN {
  print "/* This file automatically generated by element_types.awk */"
  print "enum element_type {"
  print "ET_NONE,"
}

!/^$/ && !/^#/ {
    print "ET_" $1 ","
    array = array "\"" $1 "\",\n"
}

END {
  print "};"
  print
  print "extern char *element_type_names[];"
  print "char *element_type_names[] = {" > "element_types.c"
  print "0," > "element_types.c"
  print array > "element_types.c"
  print "};" > "element_types.c"
}

function output_array (string)
{
    print string > "element_types.c"
}
